blocknotify=python /home/pi/ClockBlocker/block.py %s
walletnotify=python /home/pi/ClockBlocker/tx.py %s
rpcuser=blockclock
rpcpassword=clockerblocker
txindex=1

[regtest]
rpcport=8332
wallet=wallet.dat
fallbackfee=0.000001

[main]
wallet=wallet.dat

